### ISSUE TITLE
Problem connecting to Redis Resource

### ISSUE THREAD

**Issue by 1800joe** [noop-inc/documentation#102]
### Discussed in https://github.com/orgs/noop-inc/discussions/63

<div type='discussions-op-text'>

<sup>Originally posted by **1800joe** January 10, 2024</sup>
It appears the Service container is unable to reach the Redis resource.

Using v0.2.0

<img width="908" alt="Screenshot 2024-01-09 at 4 19 36 PM" src="https://github.com/noop-inc/documentation/assets/3111670/395f9c66-d1ce-4360-8fbd-54e69fad25f9">
</div>

**Comment by arbitrarytech** [comment]
Component->Resource networking issues are currently a priority and will be resolved in an upcoming release.
