### ISSUE TITLE
Stalled build

### ISSUE THREAD

**Issue by 1800joe** [noop-inc/documentation#105]
### Discussed in https://github.com/orgs/noop-inc/discussions/83

<div type='discussions-op-text'>

<sup>Originally posted by **1800joe** January 23, 2024</sup>
It seems like this build is stalled:

<img width="957" alt="Screenshot 2024-01-23 at 9 45 23 AM" src="https://github.com/noop-inc/documentation/assets/3111670/aac8d58d-720b-4b15-85ea-93c582ae5f7c">

The Environment can't be killed in this state.</div>

v0.5.x

**Comment by arbitrarytech** [comment]
Recent updates to clear stuck Builds on shutdown/restart may offer a way to recover. As far as the error state, nothing actionable at this time.
